Event_master/Event_master/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import index, categories

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls',  namespace = "users")),
    path('', include('mero.urls')),
    path('', include('lk.urls')),


]

Event_master/lk/urls.py
# from . import views
# from django.urls import path
# from .views import profile, event_detail
#
#
# urlpatterns= [
#     path('profile/', views.profile, name='profile'),
#     path('event/<int:event_id>/', event_detail, name='event_detail'),
#
# ]




from django.urls import path

from mero.views import event_volunteer
from .views import profile, event_register, event_unregister

urlpatterns = [
    path('profile/', profile, name='profile'),
    path('event/<int:event_id>/register/', event_register, name='event_register'),
path('event/unregister/<int:event_id>/', event_unregister, name='event_unregister'),
path('event/<int:event_id>/volunteer/', event_volunteer, name='event_volunteer'),

]

Event_master/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views


app_name = "users"
urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
]

Event_master/users/models.py
from django.db import models

# Create your models here.
# class Users(models.Model):
#     login = models.CharField(max_length=255)
#     last_name= models.CharField(max_length=255)
#     first_name=models.CharField(max_length=255)
#     middle_name=models.CharField(max_length=255)
#     birthday=models.DateTimeField()
#     genger=models.CharField(max_length=255)
#     password=models.CharField(max_length=255)

Event_master/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'LOGIN'
        })
    )
    password = forms.CharField(
        label="",
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'ПАРОЛЬ'
        })
    )


class RegisterUserForm(forms.ModelForm):
    username = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'LOGIN'
        })
    )
    password = forms.CharField(
        label="",
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Пароль'
        })
    )
    password2 = forms.CharField(
        label="",
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Повтор пароля'
        })
    )

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password', 'password2']
        labels = {
            'email': '',
            'first_name': '',
            'last_name': '',
        }
        widgets = {
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'E-mail'
            }),
            'first_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Имя'
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Фамилия'
            }),
        }





# from django import forms
# from django.contrib.auth import get_user_model
# from django.contrib.auth.forms import AuthenticationForm
#
#
# class LoginUserForm(AuthenticationForm):
#     username = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'input-group mb-3 ml-1030 mt-21 form-control', 'placeholder': 'LOGIN'}))
#     password = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'input-group mb-3 ml-1030 mt-21 form-control', 'placeholder': 'ПАРОЛЬ'}))
#
#
# # TextInput
# # PasswordInput
# # EmailInput
#
# class RegisterUserForm(forms.ModelForm):
#     username = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'input-group mb-3 ml-1030 mt-21 form-control', 'placeholder': 'LOGIN'}))
#     password = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'input-group mb-3 ml-1030 mt-21 form-control', 'placeholder': 'Пароль'}))
#     password2 = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'input-group mb-3 ml-1030 mt-21 form-control', 'placeholder': 'Повтор пароля'}))
#
#     class Meta:
#         model = get_user_model()
#         fields = ['username', 'email', 'first_name', 'last_name', 'password', 'password2']
#         labels = {
#             'email': '',
#             'first_name': '',
#             'last_name': '',
#         }
#         widgets = {
#
#             'email': forms.TextInput(attrs={'class': 'input-group mb-3 ml-1030 mt-21 form-control', 'placeholder': 'E-mail'}),
#             'first_name': forms.TextInput(attrs={'class': 'input-group mb-3 ml-1030 mt-21 form-control', 'placeholder': 'Имя'}),
#             'last_name': forms.TextInput(attrs={'class': 'input-group mb-3 ml-1030 mt-21 form-control', 'placeholder': 'Фамилия'}),
#         }
#
#
#
#         # def clean_password2(self):
#         #     cd = self.cleaned_data
#         #     if cd['password'] != cd['password2']:
#         #         raise forms.ValidationError("Пароли не совпадают!")
#         #     return cd['password2']
#         #
#         # def clean_email(self):
#         #     email = self.cleaned_data['email']
#         #     if get_user_model().objects.filter(email=email).exists():
#         #         raise forms.ValidationError("Такой E-mail уже существует!")
#         #     return email

Event_master/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import LoginUserForm, RegisterUserForm

from django.contrib.auth.models import User




class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/entrance.html'
    extra_context = {'title': "Авторизация"}


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))


def register(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)  # создание объекта без сохранения в БД
            user.set_password(form.cleaned_data['password'])
            user.save()
            return render(request, 'users/welcome.html')
    else:
        form = RegisterUserForm()
    return render(request, 'users/registration.html', {'form': form})

Event_master/users/templates/users/entrance.html
{% load static %}




<!DOCTYPE html>
<html>
  <head>
    <title>Вход | EventHub</title>
    <meta charset="utf-8" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'users/css/globals.css' %}" />
    <link rel="stylesheet" href="{% static 'users/css/style.css' %}" />
  </head>
  <body class="entrance-main">
      <section class="text-end">
        <a href="{% url 'home' %}"><img class="mt-150 mr-275" src="{% static 'users/images/EventHub.svg' %}" width="155" height="58"    alt="Логотип"></a>
        <p class="mt-42 entrance-account text-uppercase mr-220 razm">Войти в аккаунт</p>



<form method="post">
  {% csrf_token %}
  <input type="hidden" name="next" value="{{ next }}" />

  <!-- Поле логина -->
  <div class="input-group mb-3 ml-1030 mt-21">
    {{ form.username }}
  </div>

  <!-- Поле пароля -->
  <div class="input-group mb-3 ml-1030 mt-21">
    {{ form.password }}
  </div>

  <p><button type="submit" class="btn btn-warning text-white mr-300">ВОЙТИ</button></p>
</form>


<!--        <form method="post">-->
<!--          {% csrf_token %}-->
<!--          <input type="hidden" name="next" value="{{ next }}" />-->
<!--&lt;!&ndash;input-group mb-3 ml-1030 mt-21 form-control&ndash;&gt;-->
<!--          <div >-->
<!--          <p>{{ form.as_p }}</p>-->
<!--            <p><button type="submit" class="btn btn-warning text-white mr-300">ВОЙТИ</button></p>-->
<!--          </div>-->
<!--        </form>-->

<!--        <div class="input-group mb-3 ml-1030 mt-21">-->
<!--          <input type="text" class="form-control" placeholder="E-MAIL" aria-label="E-MAIL" aria-describedby="basic-addon1">-->
<!--        </div>-->
<!--        <div class="input-group mb-3 ml-1030 mt-21">-->
<!--          <input type="text" class="form-control" placeholder="ПАРОЛЬ" aria-label="ПАРОЛЬ" aria-describedby="basic-addon1">-->
<!--        </div>-->

        <a href="{% url 'users:register' %}"><p class="registration mr-225"><span class="gradient" >Зарегистрировать</span></a> новый аккаунт</p>
      </section>
  </body>
</html>



<!--<div class="input-group mb-3 ml-1030 mt-21">-->
<!--          <input type="text" class="form-control" placeholder="E-MAIL" aria-label="E-MAIL" aria-describedby="basic-addon1">-->
<!--        </div>-->
<!--        <div class="input-group mb-3 ml-1030 mt-21">-->
<!--          <input type="text" class="form-control" placeholder="ПАРОЛЬ" aria-label="ПАРОЛЬ" aria-describedby="basic-addon1">-->
<!--        </div>-->
<!--        <button type="button" class="btn btn-warning text-white mr-300">ВОЙТИ</button>-->

Event_master/users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
login
last_name
first_name
middle_name
birthday
genger
password
<form action="" method="post" target="_blank">
  {% csrf_token %}
  <h2>Шаблон формы</h2>
  <fieldset>
    <ul>
      <li>
        <label >Логин:</label>
        <input type="text" name="login" placeholder="логин" required>
      </li>
      <li>
      <label >Фамилия:</label>
        <input type="text" name="last_name" placeholder="Фамилия"  required>
      </li>
      <li>
        <label >Имя:</label>
        <input type="text" name="first_name" placeholder="Имя"  required>
      </li>
      <li>
        <label >Отчество:</label>
        <input type="text" name="middle_name" placeholder="Отчество"  required>
      </li>
        <li>
        <label >Дата рождения:</label>
        <input type="text" name="birthday" placeholder="Дата рождения"  required>
      </li>
      <li>
        <label >Пол:</label>
        <input type="text" name="genger" placeholder="Пол"  required>
      </li>
      <li>
        <label >Пароль:</label>
        <input type="text" name="password" placeholder="пароль"  required>
      </li>
    </ul>
  <div>
    <button type="submit">Отправить</button>
  </div>
    </fieldset>
</form>


</body>
</html>

Event_master/users/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>выход
</body>
</html>

Event_master/users/templates/users/registration.html
{% load static %}





<!DOCTYPE html>
<html>
  <head>
      <title>Регистрация | EventHub</title>
    <meta charset="utf-8" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'users/css/globals.css' %}" />
    <link rel="stylesheet" href="{% static 'users/css/style.css' %}" />
  </head>
  <body class="registration-main">
      <section class="text-end">
        <a href="{% url 'home' %}"><img class="mt-150 mr-275" src="{% static 'users/images/EventHub.svg' %}" width="155" height="58" href="#" alt="Логотип"></a>
        <p class="mt-42 create-account text-uppercase mr-220">Создать аккаунт</p>


       <form method="post">
  {% csrf_token %}
  <input type="hidden" name="next" value="{{ next }}" />

  <!-- Поля формы регистрации -->
  <div class="input-group mb-3 ml-1030 mt-21">
    {{ form.username }}
  </div>
  <div class="input-group mb-3 ml-1030 mt-21">
    {{ form.email }}
  </div>
  <div class="input-group mb-3 ml-1030 mt-21">
    {{ form.first_name }}
  </div>
  <div class="input-group mb-3 ml-1030 mt-21">
    {{ form.last_name }}
  </div>
  <div class="input-group mb-3 ml-1030 mt-21">
    {{ form.password }}
  </div>
  <div class="input-group mb-3 ml-1030 mt-21">
    {{ form.password2 }}
  </div>

  <p><button type="submit" class="btn btn-warning text-white mr-230">ЗАРЕГИСТРИРОВАТЬСЯ</button></p>
</form>


<!--        <form method="post">-->
<!--    {% csrf_token %}-->
<!--<input type="hidden" name="next" value="{{ next }}" />-->
<!--    {{ form.as_p }}-->
<!--    <p ><button type="submit" class="btn btn-warning text-white mr-230">ЗАРЕГИСТРИРОВАТЬСЯ</button></p>-->
<!--</form>-->



        <!--        <div class="input-group mb-3 ml-1030 mt-21">-->
<!--          <input type="text" class="form-control" placeholder="ИМЯ" aria-label="ИМЯ" aria-describedby="basic-addon1">-->
<!--        </div>-->
<!--        <div class="input-group mb-3 ml-1030 mt-21">-->
<!--          <input type="text" class="form-control" placeholder="ФАМИЛИЯ" aria-label="ФАМИЛИЯ" aria-describedby="basic-addon1">-->
<!--        </div>-->
<!--        <div class="input-group mb-3 ml-1030 mt-21">-->
<!--          <input type="text" class="form-control" placeholder="E-MAIL" aria-label="E-MAIL" aria-describedby="basic-addon1">-->
<!--        </div>-->
<!--        <div class="input-group mb-3 ml-1030 mt-21">-->
<!--          <input type="text" class="form-control" placeholder="ПАРОЛЬ" aria-label="ПАРОЛЬ" aria-describedby="basic-addon1">-->
<!--        </div>-->
<!--        <div class="input-group mb-3 ml-1030 mt-21">-->
<!--          <input type="text" class="form-control" placeholder="ПОДТВЕРДИТЬ ПАРОЛЬ" aria-label="ПОДТВЕРДИТЬ ПАРОЛЬ" aria-describedby="basic-addon1">-->
<!--        </div>-->
<!--        <button type="button" class="btn btn-warning text-white mr-230">ЗАРЕГИСТРИРОВАТЬСЯ</button>-->
        <a href="{% url 'users:login' %}"><p class="entrance1 mr-215"><span class="gradient">Войти</span></a> в уже существующий аккаунт</p>
      </section>
  </body>
</html>


<!--<div class="input-group mb-3 ml-1030 mt-21">-->
<!--          <input type="text" class="form-control" placeholder="ИМЯ" aria-label="ИМЯ" aria-describedby="basic-addon1">-->
<!--        </div>-->
<!--        <div class="input-group mb-3 ml-1030 mt-21">-->
<!--          <input type="text" class="form-control" placeholder="ФАМИЛИЯ" aria-label="ФАМИЛИЯ" aria-describedby="basic-addon1">-->
<!--        </div>-->
<!--        <div class="input-group mb-3 ml-1030 mt-21">-->
<!--          <input type="text" class="form-control" placeholder="E-MAIL" aria-label="E-MAIL" aria-describedby="basic-addon1">-->
<!--        </div>-->
<!--        <div class="input-group mb-3 ml-1030 mt-21">-->
<!--          <input type="text" class="form-control" placeholder="ПАРОЛЬ" aria-label="ПАРОЛЬ" aria-describedby="basic-addon1">-->
<!--        </div>-->
<!--        <div class="input-group mb-3 ml-1030 mt-21">-->
<!--          <input type="text" class="form-control" placeholder="ПОДТВЕРДИТЬ ПАРОЛЬ" aria-label="ПОДТВЕРДИТЬ ПАРОЛЬ" aria-describedby="basic-addon1">-->
<!--        </div>-->
<!--        <button type="button" class="btn btn-warning text-white mr-230">ЗАРЕГИСТРИРОВАТЬСЯ</button>-->

Event_master/users/templates/users/registration_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Добро пожаловать!</h1>

<p >Вы успешно зарегистрировались на сайте! Для входа в систему необходимо авторизоваться по этой <a href="{% url 'users:login' %}">ссылке</a>
</p>
</body>
</html>

Event_master/users/templates/users/welcome.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'main/css/globals.css' %}" />
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}" />
  </head>
  <body class="welcome">
    <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container text-center">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-center">
          <li class="nav-item text-center">
            <a href="{% url 'users:login' %}"><img class="navbar-brand mt-50" src="{% static 'main/images/EventHub.svg' %}"></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
    <h1 class="text-uppercase text-center mt-210">Добро пожаловать!</h1>
    <p class="text-center mt-65">Вы успешно зарегистрировались на сайте! Для входа в систему необходимо<br> авторизоваться по этой <a href="{% url 'users:login' %}"><span class="text-decoration-underline text-entrance" >ссылке.</span></a></p>
  </body>
</html>